config/routes.rb
Rails.application.routes.draw do
  #homepage route
  root :to => "pages#home"
  #new user routes
  resources :users, :only => [:new, :create,]

  #routes for logbooks & flights as a nested resource
  resources :logbooks do
    resources :flights
  end


  #log in/log out routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # routes for user chart display
  get '/users/:id/by_month' => 'users#by_month', :as => :user_by_month
  get '/users/:id/by_aircraft' => 'users#by_aircraft', :as => :user_by_aircraft
  get '/users/:id/by_type' => 'users#by_type', :as => :user_by_type

  # routes for logbook chart display
  get 'logbooks/:id/by_month' => 'logbooks#by_month', :as => :logbook_by_month
  get 'logbooks/:id/by_aircraft' => 'logbooks#by_aircraft', :as => :logbook_by_aircraft

  #routes for asynchronous charts
  resources :charts, only: [] do
    collection do
      get 'user_hours_by_month'
      get 'user_hours_by_aircraft'
      get 'user_flights_by_type'
      get 'logbook_hours_by_month'
      get 'logbook_jumps_by_month'
      get 'logbook_hours_by_aircraft'
      get 'logbook_jumps_by_canopy'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  #account security
  has_secure_password

  # table associations
  has_many :logbooks
  has_many :flights, :through => :logbooks


  # Figures out the most flown aircraft for a user for access in a view
  def most_flown_aircraft
    flights
      .group(:aircraft)
      .count
      .max_by{|k,v| v}
    end
  # Figures out the aircraft with the most flown hours for a user for access in
  # a view 
  def most_hours_aircraft
    flights
      .group(:aircraft)
      .sum(:flight_time)
      .max_by{|k,v| v}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:show, :by_month, :by_aircraft, :by_type]
  # User signup page
  def new
    # stores user shape for form helper
    @user = User.new
  end

  #creates user from user signup page details
  def create
    # fills out a user from params validated by user_params whitelist
    @user = User.new user_params
    # save the user. If it works...
    if @user.save
      # log in
      session[:user_id] = @user.id
      # go to logbooks.
      redirect_to logbooks_path
    #if the user won't save
    else
      #back to create page with errors displayed
      render :new
    end
  end

  #For statistics views, gets info to be displayed for current user
  def by_month
    @flights = @current_user.flights
  end

  def by_aircraft
    @flights = @current_user.flights
  end

  def by_type
    @flights = @current_user.flights
  end

  private
  # Whitelists what can go into params
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/users/_flights_by_type.html.erb
<%= user_flights_by_type %>
<hr class="mb-4">
<div class="statistics">
  <div class="row">
    <div class="col-md-3">
      <h4>Aviation Experience</h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-plane-departure"></i>   &nbsp; Number of Flights</h6>
      </div>
      <h4 class="text-center"><%= @flights.count %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-stopwatch"></i> &nbsp; Total Flight Time</h6>
      </div>
      <h4 class="text-center"><%= "#{@flights.sum(:flight_time).round(1)} hours" %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-hourglass-half"></i> &nbsp; Average flight Length</h6>
      </div>
      <h4 class="text-center"><%= "#{(@flights.sum(:flight_time) / @flights.count).round(1)} hours" %></h4>
    </div>
  </div>
</div>
<hr class="mb-4">

app/views/users/_hours_by_aircraft.html.erb
<%= user_hours_by_aircraft %>
<hr class="mb-4">
<div class="statistics">
  <div class="row">
    <div class="col-md-3">
      <h4>Aircraft Statistics</h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-plane-departure"></i>   &nbsp; Most Flights</h6>
      </div>
      <h4 class="text-center"><%= @current_user.most_flown_aircraft.first %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-stopwatch"></i> &nbsp; Most Flight Time</h6>
      </div>
      <h4 class="text-center"><%= @current_user.most_hours_aircraft.first  %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-hourglass-half"></i> &nbsp; Time in <%= @current_user.most_flown_aircraft.first %></h6>
      </div>
      <h4 class="text-center"><%= "#{@current_user.most_hours_aircraft[1].round(1)} hours" %></h4>
    </div>
  </div>
</div>
<hr class="mb-4">

app/views/users/_hours_by_month.html.erb
<%= user_hours_by_month %>
<hr class="mb-4">
<div class="statistics">
  <div class="row">
    <div class="col-md-3">
      <h4>Aviation Experience</h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-plane-departure"></i>   &nbsp; Number of Flights</h6>
      </div>
      <h4 class="text-center"><%= @flights.count %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-stopwatch"></i> &nbsp; Total Flight Time</h6>
      </div>
      <h4 class="text-center"><%= "#{@flights.sum(:flight_time).round(1)} hours" %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-hourglass-half"></i> &nbsp; Average flight Length</h6>
      </div>
      <h4 class="text-center"><%= "#{(@flights.sum(:flight_time) / @flights.count).round(1)} hours" %></h4>
    </div>
  </div>
</div>
<hr class="mb-4">

app/views/users/by_aircraft.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column nav-pills">
          <li class="nav-item">
            <%= link_to "Hours by Month", user_by_month_path, :class => "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Hours by Aircraft", user_by_aircraft_path, :class => "nav-link active"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Flights by Aviation Type", user_by_type_path, :class => "nav-link"  %>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2><%= "#{@current_user.first_name} #{@current_user.last_name}'s Statistics" %></h2>
      </div>
      <%= render :partial => 'hours_by_aircraft' %>
    </main>
  </div>
</div>

app/views/users/by_month.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column nav-pills">
          <li class="nav-item">
            <%= link_to "Hours by Month", user_by_month_path, :class => "nav-link active"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Hours by Aircraft", user_by_aircraft_path, :class => "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Flights by Aviation Type", user_by_type_path, :class => "nav-link"  %>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2><%= "#{@current_user.first_name} #{@current_user.last_name}'s Statistics" %></h2>
      </div>
      <%= render :partial => 'hours_by_month' %>
    </main>
  </div>
</div>

app/views/users/by_type.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column nav-pills">
          <li class="nav-item">
            <%= link_to "Hours by Month", user_by_month_path, :class => "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Hours by Aircraft", user_by_aircraft_path, :class => "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Flights by Aviation Type", user_by_type_path, :class => "nav-link active"  %>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2><%= "#{@current_user.first_name} #{@current_user.last_name}'s Statistics" %></h2>
      </div>
      <%= render :partial => 'flights_by_type' %>
    </main>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <%= form_for @user do |f| %>
  <div class="row justify-content-center">
    <div class="col-md-3 text-center ">
        <%= image_tag( "f-log_logo.png", :class => "mb-4", :alt => '', :width => "120",  ) %>
        <h2 class="h3 mb-3 font-weight-normal">Create an Account</h2>
        <% if @user.errors.any? %>
          <ul class="alert alert-warning" role="alert">
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-4 text-center form-group">
        <%= f.label :email %>
        <%= f.email_field :email, :class => "form-control" %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-2 text-center form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, :class => "form-control" %>

      </div>
      <div class="col-md-2 text-center form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, :class => "form-control" %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-4 text-center form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => "form-control" %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-4 text-center form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-4 text-center">
        <%= f.submit "Create", :class => "btn btn-lg btn-primary btn-block"  %>
      </div>
    </div>



  <% end %>
</div>