config/routes.rb
Rails.application.routes.draw do
  #homepage route
  root :to => "pages#home"
  #new user routes
  resources :users, :only => [:new, :create,]

  #routes for logbooks & flights as a nested resource
  resources :logbooks do
    resources :flights
  end


  #log in/log out routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # routes for user chart display
  get '/users/:id/by_month' => 'users#by_month', :as => :user_by_month
  get '/users/:id/by_aircraft' => 'users#by_aircraft', :as => :user_by_aircraft
  get '/users/:id/by_type' => 'users#by_type', :as => :user_by_type

  # routes for logbook chart display
  get 'logbooks/:id/by_month' => 'logbooks#by_month', :as => :logbook_by_month
  get 'logbooks/:id/by_aircraft' => 'logbooks#by_aircraft', :as => :logbook_by_aircraft

  #routes for asynchronous charts
  resources :charts, only: [] do
    collection do
      get 'user_hours_by_month'
      get 'user_hours_by_aircraft'
      get 'user_flights_by_type'
      get 'logbook_hours_by_month'
      get 'logbook_jumps_by_month'
      get 'logbook_hours_by_aircraft'
      get 'logbook_jumps_by_canopy'
    end
  end
end

app/models/logbook.rb
class Logbook < ApplicationRecord
  has_many :flights
  belongs_to :user, :optional => true
  # These are the only values allowed for logbook => aviation_type
  validates :aviation_type, inclusion: { in: ['General Aviation', 'Gliding', 'Free Flight', 'Skydiving'], message: "invalid"}

  # Figures out the most flown aircraft for a logbook for access in a view
  def most_flown_aircraft
    flights
      .group(:aircraft)
      .count
      .max_by{|k,v| v}
    end
  # Figures out the aircraft with the most flown hours for a logbook for access in
  # a view
  def most_hours_aircraft
    flights
      .group(:aircraft)
      .sum(:flight_time)
      .max_by{|k,v| v}
  end

  def most_freefall_canopy
    flights
      .group(:aircraft)
      .sum(:freefall)
      .max_by{|k,v| v}
  end
end

app/controllers/logbooks_controller.rb
class LogbooksController < ApplicationController
  before_action :check_for_login
  # shows the current user's logbook
  def index
    @logbooks = @current_user.logbooks
  end
  #Show a particular logbook
  def show
    @logbook =Logbook.find params[:id]
    @flights = @logbook.flights
    redirect_to logbooks_path if @logbook.user_id != @current_user.id
  end
  # Form for a new logbook
  def new
    @logbook = Logbook.new
  end
  # Create a new logbook from the form 'new'
  def create
    @logbook = Logbook.new logbook_params
    # If it saves, add to current user logbooks
    if @logbook.save
      @current_user.logbooks << @logbook
      # go back to logbooks index
      redirect_to logbooks_path
      # if it won't save, go back to the form
    else
      render :new
    end
  end
  # Form to edit an existing logbook
  def edit
    @logbook =Logbook.find params[:id]
  end
  # Updates logbooks from the form edit
  def update
    logbook = Logbook.find params[:id]
    logbook.update logbook_params
    redirect_to logbooks_path
  end
  # deletes a logbook
  def destroy
    logbook = Logbook.find params[:id]
    logbook.destroy
    redirect_to logbooks_path
  end
  # Shows statistics for a logbook by month
  def by_month
    @logbook =Logbook.find params[:id]
    @flights = @logbook.flights
  end
  # Shows statistics for a logbook by aircraft
  def by_aircraft
    @logbook =Logbook.find params[:id]
    @flights = @logbook.flights
  end
  # Whitelist the stuff that can go into a logbook
  private
  def logbook_params
    params.require(:logbook).permit(:name, :aviation_type, :id)
  end
end

app/views/logbooks/_form.html.erb
<% if @logbook.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @logbook.errors.full_messages.each do |msg|  %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @logbook do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :aviation_type %>
    <%= f.select:aviation_type, options_for_select(['General Aviation', 'Gliding', 'Free Flight', 'Skydiving'], @logbook.aviation_type), {}, {:class => "form-control"} %>
  </div>

  <%= f.submit :class => "btn btn-primary" %>
<% end  %>

app/views/logbooks/_free_flight.html.erb
<thead class="thead-light">
  <tr>
    <th>Date</th>
    <th>Equipment</th>
    <th>Location</th>
    <th>Launch Type</th>
    <th>Notes</th>
    <th>Duration</th>
    <th>Distance</th>
    <th>Settings</th>
  </tr>
</thead>
<tbody>
  <%=
  render partial: "free_flight_data",
  collection: @logbook.flights,
  :as => :flight
  %>
</tbody>
<thead class="thead-light">
  <th colspan="5" class="align-middle"> Totals</th>
  <th class="align-middle">
    <%= "#{@flights.sum(:flight_time).round(1)} hrs" %>
  </th>
  <th class="align-middle">
    <%=  "#{@flights.sum(:distance).round(1)} Km" %>
  </th>
  <th class="align-middle">Hours</th>
</thead>

app/views/logbooks/_free_flight_data.html.erb
<tr>
  <td><%= flight.date %></td>
  <td><%= flight.aircraft %></td>
  <td><%= flight.location %></td>
  <td><%= flight.launch_type %></td>
  <td><%= flight.notes %></td>
  <td><%= flight.flight_time%></td>
  <td><%= flight.distance %></td>
  <td>
    <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    ...
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to 'Delete', logbook_flight_path(@logbook.id, flight.id), :method  => 'delete', :class => "dropdown-item" %>
    <%= link_to 'Edit', edit_logbook_flight_path(@logbook.id, flight.id), :class => "dropdown-item"  %>
  </div>
  </td>
</tr>

app/views/logbooks/_general_aviation.html.erb
<thead class="thead-light">
  <tr>
    <th rowspan="3" class="align-middle">Date</th>
    <th colspan="2" class="align-middle">Aircraft</th>
    <th rowspan="3" class="align-middle">Notes</th>
    <th colspan="4" class="align-middle">Single Engine</th>
    <th colspan="4" class="align-middle">Multi Engine</th>
    <th rowspan="3" class="align-middle">Instrument</th>
    <th rowspan="3" class="align-middle">Settings</th>
  </tr>
  <tr>
    <th rowspan="2" class="align-middle"><small>Type</small></th>
    <th rowspan="2" class="align-middle"><small>Registration</small></th>
    <th colspan="2" class="align-middle"><small>Dual</small></th>
    <th colspan="2" class="align-middle"><small>Command</small></th>
    <th colspan="2" class="align-middle"><small>Dual</small></th>
    <th colspan="2" class="align-middle"><small>Command</small></th>
  </tr>
  <tr>
    <th><small>Day</small></th>
    <th><small>Night</small></th>
    <th><small>Day</small></th>
    <th><small>Night</small></th>
    <th><small>Day</small></th>
    <th><small>Night</small></th>
    <th><small>Day</small></th>
    <th><small>Night</small></th>
  </tr>
</thead>
<!-- Fill data by flight -->
<tbody>
  <%=
  render partial: "general_aviation_data",
  collection: @logbook.flights,
  :as => :flight
  %>
</tbody>
<thead class="thead-light">
  <th colspan="4" class="align-middle"> Totals</th>
  <th class="align-middle">
    <%= @flights.where(:multi => false, :command => false, :night => false).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => false, :command => false, :night => true).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => false, :command => true, :night => false).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => false, :command => true, :night => true).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => true, :command => false, :night => false).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => true, :command => false, :night => true).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => true, :command => true, :night => false).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:multi => true, :command => true, :night => true).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle"><%= "#{@flights.sum(:instrument_time).round(1)}" %></th>
  <th class="align-middle">Hours</th>
</thead>

app/views/logbooks/_general_aviation_data.html.erb
<tr>
  <td><%= flight.date %></td>
  <td><%= flight.aircraft %></td>
  <td><%= flight.registration %></td>
  <td><%= flight.notes %></td>
  <td><%= flight.flight_time if !flight.multi && !flight.command && !flight.night %></td>
  <td><%= flight.flight_time if !flight.multi && !flight.command && flight.night %></td>
  <td><%= flight.flight_time if !flight.multi && flight.command && !flight.night %></td>
  <td><%= flight.flight_time if !flight.multi && flight.command && flight.night %></td>
  <td><%= flight.flight_time if flight.multi && !flight.command && !flight.night %></td>
  <td><%= flight.flight_time if flight.multi && !flight.command && flight.night %></td>
  <td><%= flight.flight_time if flight.multi && flight.command && !flight.night %></td>
  <td><%= flight.flight_time if flight.multi && flight.command && flight.night %></td>
  <td><%= flight.instrument_time %></td>
  <td>
    <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    ...
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to 'Delete', logbook_flight_path(@logbook.id, flight.id), :method  => 'delete', :class => "dropdown-item" %>
    <%= link_to 'Edit', edit_logbook_flight_path(@logbook.id, flight.id), :class => "dropdown-item"  %>
  </div>
  </td>
</tr>

app/views/logbooks/_gliding.html.erb
<thead class="thead-light">
  <tr>
    <th rowspan="2" class="align-middle">Date</th>
    <th colspan="2" class="align-middle">Aircraft</th>
    <th rowspan="2" class="align-middle">Location</th>
    <th rowspan="2" class="align-middle">Launch Type</th>
    <th rowspan="2" class="align-middle">Notes</th>
    <th rowspan="2" class="align-middle">Dual Time</th>
    <th rowspan="2" class="align-middle">Solo Time</th>
    <th rowspan="2" class="align-middle">Settings</th>
  </tr>
  <tr>
    <th><small>Type</small></th>
    <th><small>Registration</small></th>
  </tr>
</thead>
<tbody>
  <%=
  render partial: "gliding_data",
  collection: @logbook.flights,
  :as => :flight
  %>
</tbody>
<thead class="thead-light">
  <th colspan="6" class="align-middle"> Totals</th>
  <th class="align-middle">
    <%= @flights.where(:command => false).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">
    <%=  @flights.where(:command => true).sum(:flight_time).round(1) %>
  </th>
  <th class="align-middle">Hours</th>
</thead>

app/views/logbooks/_gliding_data.html.erb
<tr>
  <td><%= flight.date %></td>
  <td><%= flight.aircraft %></td>
  <td><%= flight.registration %></td>
  <td><%= flight.location %></td>
  <td><%= flight.launch_type %></td>
  <td><%= flight.notes %></td>
  <td><%= flight.flight_time if !flight.command %></td>
  <td><%= flight.flight_time if flight.command %></td>
  <td>
    <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    ...
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to 'Delete', logbook_flight_path(@logbook.id, flight.id), :method  => 'delete', :class => "dropdown-item" %>
    <%= link_to 'Edit', edit_logbook_flight_path(@logbook.id, flight.id), :class => "dropdown-item"  %>
  </div>
  </td>
</tr>

app/views/logbooks/_hours_by_aircraft.html.erb
<%= logbook_hours_by_aircraft %>
<hr class="mb-4">
<div class="statistics">
  <div class="row">
    <div class="col-md-3">
      <h4><%= "#{@logbook.name} Stats" %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-plane-departure"></i>   &nbsp; Most Flights</h6>
      </div>
      <h4 class="text-center"><%= @logbook.most_flown_aircraft.first %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-stopwatch"></i> &nbsp; Most flight time</h6>
      </div>
      <h4 class="text-center"><%=  @logbook.most_hours_aircraft.first %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-hourglass-half"></i> &nbsp; Time in <%= @logbook.most_hours_aircraft.first %></h6>
      </div>
      <h4 class="text-center"><%= "#{@logbook.most_hours_aircraft[1].round(1)} hours" %></h4>
    </div>
  </div>
</div>
<hr class="mb-4">

app/views/logbooks/_hours_by_month.html.erb
<%= logbook_hours_by_month %>
<hr class="mb-4">
<div class="statistics">
  <div class="row">
    <div class="col-md-3">
      <h4><%= "#{@logbook.name} Stats" %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-plane-departure"></i>   &nbsp; Number of Flights</h6>
      </div>
      <h4 class="text-center"><%= @flights.count %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-stopwatch"></i> &nbsp; Total Flight Time</h6>
      </div>
      <h4 class="text-center"><%= "#{@flights.sum(:flight_time).round(1)} hours" %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-hourglass-half"></i> &nbsp; Average flight Length</h6>
      </div>
      <h4 class="text-center"><%= "#{(@flights.sum(:flight_time) / @flights.count).round(1)} hours" %></h4>
    </div>
  </div>
</div>
<hr class="mb-4">

app/views/logbooks/_jumps_by_canopy.html.erb
<%= logbook_jumps_by_canopy %>
<hr class="mb-4">
<div class="statistics">
  <div class="row">
    <div class="col-md-3">
      <h4><%= "#{@logbook.name} Stats" %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-plane-departure"></i>   &nbsp; Canopy with Most Jumps</h6>
      </div>
      <h4 class="text-center"><%= @logbook.most_flown_aircraft.first %></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-stopwatch"></i> &nbsp; Canopy with most freefall time</h6>
      </div>
      <h4 class="text-center"><%= @logbook.most_freefall_canopy.first%></h4>
    </div>
    <div class="col-md-3">
      <div class="heading">
        <h6 class="text-center"><i class="fas fa-cloud"></i> &nbsp; Total freefall time with <%= @logbook.most_freefall_canopy.first %>  </h6>
      </div>
      <h4 class="text-center"><%= "#{@logbook.most_freefall_canopy[1] / 60} minutes" %></h4>
    </div>
  </div>
</div>
<hr class="mb-4">

app/views/logbooks/by_aircraft.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column nav-pills">
          <li class="nav-item">
            <% if @logbook.aviation_type == 'Skydiving' %>
            <%= link_to "Jumps by Month", logbook_by_month_path, :class => "nav-link"  %>
            <% else %>
            <%= link_to "Hours by Month", logbook_by_month_path, :class => "nav-link"  %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if @logbook.aviation_type == 'Skydiving' %>
            <%= link_to "Jumps by Canopy", logbook_by_aircraft_path, :class => "nav-link active"  %>
            <% else %>
            <%= link_to "Hours by Aircraft", logbook_by_aircraft_path, :class => "nav-link active"  %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2><%= "#{@logbook.name} Statistics" %></h2>
      </div>
      <% if @logbook.aviation_type == 'Skydiving' %>
      <%= render :partial => 'jumps_by_canopy' %>
      <% else %>
      <%= render :partial => 'hours_by_aircraft' %>
      <% end %>
    </main>
  </div>
</div>

app/views/logbooks/edit.html.erb
<div class="container">
  <h2>Edit '<%= @logbook.name %>' logbook</h2>

  <%= render :partial => 'form' %>  
</div>

app/views/logbooks/new.html.erb
<div class="container">
  <h2>Create a new logbook</h2>

  <%= render :partial => 'form' %>
</div>

app/views/logbooks/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <div><h2><%= @logbook.name %></h2></div>
    <div><%= button_to "New Flight", new_logbook_flight_path(@logbook.id), :method => 'get',  :class => "btn btn-primary btn-sm" %></div>
  </div>

  <div class="table-responsive">
    <table class="table table-bordered table-sm text-center">
      <!-- Display logbook format for each type -->
      <% if @logbook.aviation_type == 'General Aviation' %>
        <%= render partial: "general_aviation" %>
      <% elsif @logbook.aviation_type == 'Gliding' %>
        <%= render partial: "gliding" %>
      <% elsif @logbook.aviation_type == 'Free Flight' %>
        <%= render partial: "free_flight" %>
      <% elsif @logbook.aviation_type == 'Skydiving' %>
        <%= render partial: "skydiving" %>
      <% end %>
    </table>
  </div>
</div>