config/routes.rb
Rails.application.routes.draw do
  #homepage route
  root :to => "pages#home"
  #new user routes
  resources :users, :only => [:new, :create,]

  #routes for logbooks & flights as a nested resource
  resources :logbooks do
    resources :flights
  end


  #log in/log out routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # routes for user chart display
  get '/users/:id/by_month' => 'users#by_month', :as => :user_by_month
  get '/users/:id/by_aircraft' => 'users#by_aircraft', :as => :user_by_aircraft
  get '/users/:id/by_type' => 'users#by_type', :as => :user_by_type

  # routes for logbook chart display
  get 'logbooks/:id/by_month' => 'logbooks#by_month', :as => :logbook_by_month
  get 'logbooks/:id/by_aircraft' => 'logbooks#by_aircraft', :as => :logbook_by_aircraft

  #routes for asynchronous charts
  resources :charts, only: [] do
    collection do
      get 'user_hours_by_month'
      get 'user_hours_by_aircraft'
      get 'user_flights_by_type'
      get 'logbook_hours_by_month'
      get 'logbook_jumps_by_month'
      get 'logbook_hours_by_aircraft'
      get 'logbook_jumps_by_canopy'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Include FontAwesome -->
    <script src="https://kit.fontawesome.com/5986bf02eb.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <!-- Create a dark navbar at the top of the page -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <!-- If a user is logged in, show appropriate links -->
        <% if @current_user.present? %>
        <!-- Logo links to logbooks index. First so logo always displays -->
        <%= link_to image_tag( "f-log_logo.png", :height => 30, :alt => '', ), logbooks_path %>
        <!-- Bootstrap collapse for smaller screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <!-- Navbar links -->
            <ul class="navbar-nav">
              <li class= <%= 'active' if current_page?(logbooks_path) %>>
                <!-- Link to logbooks index. Will show active -->
                <%= link_to 'My Logbooks', logbooks_path, :class => "nav-item nav-link" %>
              </li>
              <!-- Dropdown links to statistics pages. Will show active -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Statistics
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "User Statistics", user_by_month_path(@current_user), :class => "dropdown-item" %>
                <div class="dropdown-divider"></div>
                  <% @current_user.logbooks.each do |logbook| %>
                    <%= link_to "#{logbook.name} statistics", logbook_by_month_path(logbook), :class => "dropdown-item" %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item">
                <!-- Link to logout.  -->
                <%= link_to "Log out of #{@current_user.first_name} #{@current_user.last_name}", login_path, :method => 'delete', :class => "nav-item nav-link" %>
              </li>
            </ul>
          </div>
          <!-- if logged out show links to create acc/log in -->
        <% else %>
        <%= link_to image_tag( "f-log_logo.png",  :height => 30, :alt => '' ), root_path %>
        <!-- Bootstrap collapse for smaller screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <!-- Navbar links -->
            <ul class="navbar-nav">
              <li class=<%= "active" if current_page?(new_user_path)  %>>
                <%= link_to 'Create Account', new_user_path, :class => "nav-item nav-link" %>
              </li>
              <li  class=<%= "active" if current_page?(login_path) %> >
                <%= link_to 'Log In', login_path, :class => "nav-item nav-link" %>
              </li>
            </ul>
          </div>
        <% end %>
      </nav>
    </header>


      <!-- No container here because it's in the views for targeted styling -->
      <%= yield %>


    <footer class="footer">
      <div class="container">
        <!-- splits footer items to either side of the footer -->
        <div class="text-muted d-flex justify-content-between align-items-center">
          <!-- byline -->
          <div>Nick Mather for General Assembly Australia SEI #38, October 2020.</div>
          <!-- social links -->
          <div>
            <a href="https://twitter.com/Forcebe_" target="_blank" class="text-secondary">
              <i class="fa fa-twitter"></i>
            </a>
            <a href="https://www.linkedin.com/in/nicholas-mather-5631091b4/" target="_blank" class="text-secondary">
              <i class="fa fa-linkedin"></i>
            </a>
            <a href="https://medium.com/@nickmather12" target="_blank" class="text-secondary">
              <i class="fa fa-medium"></i>
            </a>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>